# -*- coding: utf-8 -*-
"""INSE_6220_Project_NSL_KDD_report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Zarchi1992/INSE-6220-2254-WinterSemester-40337033/blob/main/INSE_6220_Project_NSL_KDD_report.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style="darkgrid")
import pandas as pd
plt.rcParams['figure.figsize'] = (7,5)

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

print("Pandas version: ", pd.__version__)
print("Seaborn version: ", sns.__version__)

!pip install kaggle==1.6.14

import os
os.environ["KAGGLE_API_TOKEN"] = "KGAT_b98dbaffe8b47c95f916375da5eb7b87"

!kaggle datasets download -d hassan06/nslkdd
!unzip -o nslkdd.zip

columns = [
    "duration","protocol_type","service","flag","src_bytes","dst_bytes","land",
    "wrong_fragment","urgent","hot","num_failed_logins","logged_in",
    "num_compromised","root_shell","su_attempted","num_root",
    "num_file_creations","num_shells","num_access_files","num_outbound_cmds",
    "is_host_login","is_guest_login","count","srv_count","serror_rate",
    "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
    "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate","dst_host_srv_diff_host_rate",
    "dst_host_serror_rate","dst_host_srv_serror_rate","dst_host_rerror_rate",
    "dst_host_srv_rerror_rate","label","level"
]

train_df = pd.read_csv("KDDTrain+.txt", header=None, names=columns)
test_df  = pd.read_csv("KDDTest+.txt", header=None, names=columns)

train_df = train_df.drop(columns=["level"])
test_df  = test_df.drop(columns=["level"])

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

print("Number of original features:", train_df.shape[1] - 1)

train_df.info()

train_df.shape

print("Number of duplicated rows is: ", train_df.duplicated().sum())

print("Number of rows with NaNs is: ", train_df.isna().any(axis=1).sum())

dos_attacks = {
    "back","land","neptune","pod","smurf","teardrop",
    "mailbomb","apache2","processtable","udpstorm","worm"
}

probe_attacks = {
    "satan","ipsweep","nmap","portsweep","mscan","saint"
}

r2l_attacks = {
    "ftp_write","guess_passwd","imap","multihop","phf","spy",
    "warezclient","warezmaster","sendmail","named","snmpgetattack",
    "snmpguess","xlock","xsnoop","httptunnel"
}

u2r_attacks = {
    "buffer_overflow","loadmodule","perl","rootkit","ps","sqlattack","xterm"
}

def map_attack_group(label):
    if label == "normal":
        return "normal"
    elif label in dos_attacks:
        return "dos"
    elif label in probe_attacks:
        return "probe"
    elif label in r2l_attacks:
        return "r2l"
    elif label in u2r_attacks:
        return "u2r"
    else:
        return "other"

train_df["attack_group"] = train_df["label"].apply(map_attack_group)
test_df["attack_group"]  = test_df["label"].apply(map_attack_group)

print("\nRaw label distribution:")
print(train_df["label"].value_counts().head(20))

print("\nGrouped multiclass distribution:")
print(train_df["attack_group"].value_counts())

train_df["attack_group"] = train_df["label"].apply(map_attack_group)
test_df["attack_group"]  = test_df["label"].apply(map_attack_group)

# Distribution
train_counts = train_df["attack_group"].value_counts()
test_counts  = test_df["attack_group"].value_counts()

print(train_counts)
print(test_counts)

plt.figure(figsize=(6,6))
plt.pie(train_counts, labels=train_counts.index, autopct='%1.1f%%', startangle=90)
plt.title("Train Data Distribution")

plt.savefig("train_distribution.pdf", bbox_inches='tight')
plt.savefig("train_distribution.png", dpi=600, bbox_inches='tight')
plt.show()

train_counts_combined = train_counts.copy()

train_counts_combined['u2r+r2l'] = (
    train_counts_combined.get('u2r', 0) +
    train_counts_combined.get('r2l', 0)
)

train_counts_combined = train_counts_combined.drop(['u2r', 'r2l'], errors='ignore')

plt.figure(figsize=(7, 5))

plt.pie(
    train_counts_combined,
    labels=train_counts_combined.index,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={'edgecolor': 'white', 'linewidth': 1}
)

plt.title("Train Data Distribution")
plt.tight_layout()

plt.savefig("train_distribution.png", dpi=600, bbox_inches='tight')
plt.savefig("train_distribution.pdf", bbox_inches='tight')

plt.show()

from google.colab import files
files.download("train_distribution.pdf")

plt.figure(figsize=(7, 5))

plt.pie(test_counts,
        labels=test_counts.index,
        autopct='%1.1f%%',
        startangle=90)

plt.title("Test Data Distribution")
plt.tight_layout()

plt.savefig("test_distribution.png", dpi=600, bbox_inches='tight')
plt.savefig("test_distribution.pdf", bbox_inches='tight')

plt.show()

from google.colab import files
files.download("test_distribution.pdf")

X = train_df.drop(columns=["label", "attack_group"])
y = train_df["attack_group"]

# Identify categorical columns
categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()

# One-hot encoding
X_encoded = pd.get_dummies(X, columns=categorical_cols)

print("Encoded feature count:", X_encoded.shape[1])

# Standardization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_encoded)

# Convert to DataFrame (IMPORTANT for next steps)
X_scaled_df = pd.DataFrame(X_scaled, columns=X_encoded.columns)

corr_matrix = X_scaled_df.corr().abs()

top_features = corr_matrix.sum().sort_values(ascending=False).head(10).index.tolist()

print(top_features)

sns.pairplot(
    X_scaled_df[top_features].assign(attack_group=y.values),
    hue="attack_group",
    diag_kind="kde"
)

plt.savefig("pairplot_top10_corr.pdf", bbox_inches="tight")
plt.show()

corr_matrix = X_scaled_df.corr().abs()

# Select top 10 features
top_features = corr_matrix.sum().sort_values(ascending=False).head(5).index.tolist()

print("Top 5 features:", top_features)

# Pairplot
import seaborn as sns

sns.pairplot(
    X_scaled_df[top_features].assign(attack_group=y.values),
    hue="attack_group",
    diag_kind="kde"
)

plt.savefig("pairplot_top5.pdf", bbox_inches="tight")
plt.show()

files.download('pairplot_top5.pdf')

pca_model = PCA(n_components=0.95)
Z = pca_model.fit_transform(X_scaled_df)

print("Original features:", X.shape[1])
print("Encoded features:", X_encoded.shape[1])
print("Reduced PCA features:", Z.shape[1])

numeric_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

plt.figure(figsize=(18, 6))
sns.boxplot(data=X_scaled_df[numeric_cols], orient="v")
plt.xticks(rotation=90)
plt.title("Box Plot of Numeric Features")
plt.tight_layout()
plt.show()

corr_abs = X_scaled_df.corr().abs()

top_15_features = corr_abs.sum().sort_values(ascending=False).head(15).index.tolist()

print("Top 15 correlated features:")
print(top_15_features)

plt.figure(figsize=(7, 5))
sns.boxplot(data=X_scaled_df[top_15_features], orient="v")

plt.xticks(rotation=90)
plt.title("Box Plot of Top 15 Correlated Features")

plt.tight_layout()
plt.savefig("boxplot_top15_features.pdf", bbox_inches="tight")
plt.savefig("boxplot_top15_features.png", dpi=600, bbox_inches="tight")

plt.show()

from google.colab import files
files.download("boxplot_top15_features.png")

y_group = train_df["attack_group"]

# Use ONLY numeric columns for this selection
X_num = X_scaled_df.loc[train_df.index]  # align indices if needed

# Compute ANOVA F-score (multiclass)
F, p = f_classif(X_num, y_group)
feature_rank = pd.Series(F, index=X_num.columns).sort_values(ascending=False)

top_features = feature_rank.head(15).index.tolist()
top_features

plot_df = train_df[["attack_group"]].join(X_scaled_df[top_features])

long_df = plot_df.melt(id_vars="attack_group", var_name="Feature", value_name="Value")

plt.figure(figsize=(10,5))
sns.boxplot(data=long_df, x="Feature", y="Value", hue="attack_group")
plt.xticks(rotation=90)
plt.title("Top features across attack groups")
plt.legend(title="attack_group", bbox_to_anchor=(1.02,1), loc="upper left")
plt.tight_layout()
plt.savefig("Box_TopFeatures_by_AttackGroup.png", dpi=600, bbox_inches="tight")
plt.savefig("Box_TopFeatures_by_AttackGroup.pdf", bbox_inches="tight")
plt.show()
plt.close()

files.download("Box_TopFeatures_by_AttackGroup.pdf")

plt.figure(figsize=(10,6))

sns.boxplot(
    data=long_df,
    x="Value",          # numeric axis
    y="Feature",        # feature names
    hue="attack_group",
    orient="h"
)

plt.title("Top features across attack groups")
plt.legend(
    title="attack_group",
    bbox_to_anchor=(1.02, 1),
    loc="upper left"
)

plt.tight_layout()
plt.savefig("Box_TopFeatures_by_AttackGroup_horizontal.png", dpi=600, bbox_inches="tight")
plt.savefig("Box_TopFeatures_by_AttackGroup_horizontal.pdf", bbox_inches="tight")

plt.show()
plt.close()

plt.figure(figsize=(9,6))
sns.boxplot(data=X_scaled_df[top_features], orient="h")
plt.title("Top features (scaled) - horizontal boxplot")
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,5))
sns.boxplot(data=long_df, x="Feature", y="Value", hue="attack_group", showfliers=False)
plt.xticks(rotation=90)
plt.title("Top features across attack groups (outliers hidden)")
plt.tight_layout()
plt.show()

plt.figure(figsize=(7, 5))

ax = sns.boxplot(
    data=X_scaled_df[top_15_features],
    orient="v",
    palette="Set2"
)

sns.stripplot(
    data=X_scaled_df[top_15_features],
    color=".25",
    size=2,          # smaller points
    jitter=True,     # spread points
    alpha=0.5        # transparency
)

ax.tick_params(axis='x', labelrotation=90)

plt.title("Box Plot + Strip Plot of Top 15 Features")

plt.tight_layout()
plt.savefig("boxplot_top15_features.pdf", bbox_inches="tight")
plt.savefig("boxplot_top15_features.png", dpi=600, bbox_inches="tight")

plt.show()

corr = X_scaled_df[numeric_cols].corr()

plt.figure(figsize=(16, 12))
sns.heatmap(corr, cmap="RdYlGn_r", linewidths=0.2)
plt.title("Correlation Matrix (Numeric Features)")
plt.tight_layout()
plt.savefig("correlation_numeric_features.pdf", bbox_inches="tight")
plt.savefig("correlation_numeric_features.png", dpi=600, bbox_inches="tight")
plt.show()

corr_abs = X_scaled_df.corr().abs()
top_corr_features = corr_abs.sum().sort_values(ascending=False).head(10).index.tolist()

print("Top 10 correlated features:")
print(top_corr_features)

plt.figure(figsize=(10, 8))
sns.heatmap(X_scaled_df[top_corr_features].corr(), annot=True, cmap="RdYlGn_r", linewidths=0.2)
plt.title("Correlation Matrix of Top 10 Correlated Features")
plt.tight_layout()
plt.savefig("correlation_top_features.pdf", bbox_inches="tight")
plt.savefig("correlation_top_features.png", dpi=600, bbox_inches="tight")
plt.show()

from google.colab import files
files.download("correlation_top_features.pdf")

# PCA dataframe
pca_df = pd.DataFrame(Z, columns=[f"PC{i+1}" for i in range(Z.shape[1])])

# Add class label for plotting
pca_plot_df = pca_df.copy()
pca_plot_df["attack_group"] = y.values

plt.figure(figsize=(7, 5))
sns.scatterplot(
    data=pca_plot_df,
    x="PC1",
    y="PC2",
    hue="attack_group",
    alpha=0.7
)
plt.title("PCA Scatter Plot (PC1 vs PC2)")
plt.tight_layout()
plt.savefig("PCA_Scatter_Plot.pdf", bbox_inches="tight")
plt.savefig("PCA_Scatter_Plot.png", dpi=600, bbox_inches="tight")
plt.show()

plt.figure(figsize=(7,5))
sns.boxplot(data=X_scaled_df[top_corr_features], orient="v")
plt.xticks(rotation=90)
plt.title("Box Plot of Top Correlated Features")
plt.tight_layout()
plt.savefig("boxplot_top_features.pdf", bbox_inches="tight")
plt.savefig("boxplot_top_features.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(7,5))

sns.heatmap(
    X_scaled_df[top_corr_features].corr(),
    cmap="RdYlGn_r",
    annot=True,
    fmt=".2f",
    annot_kws={"size": 7},
    linewidths=0.5
)

plt.xticks(rotation=45, ha="right", fontsize=8)
plt.yticks(fontsize=8)

plt.title("Correlation Matrix of Top Correlated Features", fontsize=12)
plt.tight_layout()

plt.savefig("correlation_top_features.pdf", bbox_inches="tight")
plt.show()

feat_cols = top_features  # or numeric_cols, or top 15/20 features

groups = ["normal","dos","probe","r2l","u2r"]

for g in groups:
    sub_idx = train_df["attack_group"] == g
    sub = X_scaled_df.loc[sub_idx, feat_cols]

    # Correlation
    corr_g = sub.corr()

    plt.figure(figsize=(8,6))
    sns.heatmap(corr_g, cmap="RdYlGn_r", center=0, linewidths=0.2, square=True)
    plt.title(f"Correlation Matrix ({g}) – Selected Features")
    plt.tight_layout()
    plt.savefig(f"Fig_Corr_{g}.png", dpi=600, bbox_inches="tight")
    plt.show()
    plt.close()

from google.colab import files
files.download("Fig_Corr_u2r.png")

variables = X_scaled_df.columns
A = pca_model.components_.T

# contribution strength based on PC1 and PC2
loading_strength = np.sqrt(A[:, 0]**2 + A[:, 1]**2)

# select top 10 features
top_n = 10
top_idx = np.argsort(loading_strength)[-top_n:]

plt.figure(figsize=(8, 6))
plt.scatter(A[top_idx, 0], A[top_idx, 1])

for i in top_idx:
    plt.annotate(
        variables[i],
        (A[i, 0], A[i, 1]),
        xytext=(5, 5),
        textcoords='offset points'
    )

plt.axhline(0, linestyle='--', linewidth=0.8)
plt.axvline(0, linestyle='--', linewidth=0.8)
plt.xlabel('PC1 Loadings')
plt.ylabel('PC2 Loadings')
plt.title(f'Top {top_n} Feature Loadings on PC1 and PC2')
plt.tight_layout()
plt.savefig("Top_Feature_Loadings.pdf", bbox_inches="tight")
plt.savefig("Top_Feature_Loadings.png", dpi=600, bbox_inches="tight")
plt.show()

loadings = pd.DataFrame(
    pca_model.components_.T,
    columns=[f"PC{i+1}" for i in range(pca_model.components_.shape[0])],
    index=X_scaled_df.columns
)

# Top features contributing to PC1 and PC2
top_n = 15
top_features = (
    loadings[["PC1", "PC2"]]
    .assign(loading_strength=lambda d: (d["PC1"]**2 + d["PC2"]**2) ** 0.5)
    .sort_values("loading_strength", ascending=False)
    .head(top_n)
)

plt.figure(figsize=(10, 8))
plt.scatter(top_features["PC1"], top_features["PC2"])

for feat, x, y in zip(top_features.index, top_features["PC1"], top_features["PC2"]):
    plt.annotate(
        feat,
        (x, y),
        xytext=(3, 3),
        textcoords="offset points",
        fontsize=9
    )

plt.axhline(0, linestyle="--", linewidth=0.8)
plt.axvline(0, linestyle="--", linewidth=0.8)
plt.xlabel("PC1 Loading")
plt.ylabel("PC2 Loading")
plt.title(f"Top {top_n} Feature Loadings on PC1 and PC2")
plt.tight_layout()

plt.savefig("Top_Feature_Loadings.pdf", bbox_inches="tight")
plt.savefig("Top_Feature_Loadings.png", dpi=600, bbox_inches="tight")
plt.show()

explained_variance_ratio = pca_model.explained_variance_ratio_
eigenvalues = pca_model.explained_variance_
x_axis = np.arange(1, len(eigenvalues) + 1)

plt.figure(figsize=(7, 5))
plt.plot(x_axis, explained_variance_ratio, "o-")
plt.xlabel("Number of Components")
plt.ylabel("Explained Variance Ratio")
plt.title("Scree Plot")
plt.tight_layout()
plt.savefig("scree_plot_full.pdf", bbox_inches="tight")
plt.savefig("scree_plot_full.png", dpi=300, bbox_inches="tight")
plt.show()

pca_model = PCA()
Z = pca_model.fit_transform(X_scaled_df)

explained_variance_ratio = pca_model.explained_variance_ratio_
cumulative_variance = np.cumsum(explained_variance_ratio)

n_show = 30

plt.figure(figsize=(7,5))
plt.plot(range(1, n_show+1), explained_variance_ratio[:n_show], marker="o")
plt.xlabel("Principal Component")
plt.ylabel("Explained Variance Ratio")
plt.title("Scree Plot (First 30 Components)")
plt.tight_layout()
plt.savefig("scree_plot.pdf", bbox_inches="tight")
plt.savefig("scree_plot.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(7,5))
plt.bar(range(1, n_show+1), explained_variance_ratio[:n_show], alpha=0.6, label="Individual")
plt.plot(range(1, len(cumulative_variance)+1), cumulative_variance, marker="o", color="red", label="Cumulative")
plt.axhline(y=0.85, color="green", linestyle="--", label="85% variance")
plt.axhline(y=0.95, color="purple", linestyle="--", label="95% variance")
plt.xlabel("Number of Components")
plt.ylabel("Explained Variance")
plt.title("Explained Variance and Cumulative Variance")
plt.legend()
plt.tight_layout()
plt.savefig("explained_variance.pdf", bbox_inches="tight")
plt.savefig("explained_variance.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(7, 5))

sns.scatterplot(
    data=pca_plot_df.sample(min(5000, len(pca_plot_df)), random_state=42),
    x="PC1",
    y="PC2",
    hue="attack_group",
    alpha=0.5,
    legend=True
)

scale_x = pca_plot_df["PC1"].abs().max()
scale_y = pca_plot_df["PC2"].abs().max()

for feat in top_features.index:
    plt.arrow(
        0, 0,
        top_features.loc[feat, "PC1"] * scale_x * 0.8,
        top_features.loc[feat, "PC2"] * scale_y * 0.8,
        head_width=0.15,
        alpha=0.7
    )
    plt.text(
        top_features.loc[feat, "PC1"] * scale_x * 0.9,
        top_features.loc[feat, "PC2"] * scale_y * 0.9,
        feat,
        fontsize=9
    )

plt.title("Biplot (Top 15 Features)")
plt.tight_layout()
plt.savefig("biplot_top15_features.pdf", bbox_inches="tight")
plt.savefig("biplot_top15_features.png", dpi=600, bbox_inches="tight")
plt.show()

pca_model = PCA(n_components=2, random_state=42)
Z_2d = pca_model.fit_transform(X_scaled_df)

pca_plot_df = pd.DataFrame(
    Z_2d,
    columns=["PC1", "PC2"],
    index=train_df.index
)

pca_plot_df["attack_group"] = train_df["attack_group"].values

loadings = (
    pca_model.components_.T *
    np.sqrt(pca_model.explained_variance_)
)

loadings_df = pd.DataFrame(
    loadings,
    index=X_scaled_df.columns,
    columns=[f"PC{i+1}" for i in range(loadings.shape[1])]
)

loading_strength = (
    loadings_df[["PC1", "PC2"]]
    .abs()
    .sum(axis=1)
)

top_feature_names = loading_strength.sort_values(
    ascending=False
).head(15).index

top_loadings = loadings_df.loc[top_feature_names, ["PC1", "PC2"]]

plt.figure(figsize=(7,5))

sns.scatterplot(
    data=pca_plot_df.sample(min(5000, len(pca_plot_df)), random_state=42),
    x="PC1",
    y="PC2",
    hue="attack_group",
    alpha=0.45,
    legend=True
)

# Scale arrows
scale_x = pca_plot_df["PC1"].abs().max()
scale_y = pca_plot_df["PC2"].abs().max()

for feat in top_loadings.index:
    plt.arrow(
        0, 0,
        top_loadings.loc[feat, "PC1"] * scale_x * 0.7,
        top_loadings.loc[feat, "PC2"] * scale_y * 0.7,
        head_width=0.08,
        alpha=0.6,
        color="black",
        linewidth=1
    )
    plt.text(
        top_loadings.loc[feat, "PC1"] * scale_x * 0.75,
        top_loadings.loc[feat, "PC2"] * scale_y * 0.75,
        feat,
        fontsize=8
    )

evr = pca_model.explained_variance_ratio_
plt.xlabel(f"PC1 ({evr[0]*100:.1f}% variance)")
plt.ylabel(f"PC2 ({evr[1]*100:.1f}% variance)")
plt.title("PCA Biplot (Top Features by Loadings)")

plt.tight_layout()
plt.savefig("biplot_top_features.png", dpi=600, bbox_inches="tight")
plt.savefig("biplot_top_features.pdf", bbox_inches="tight")
plt.show()
plt.close()

files.download('biplot_top_features.png')

!pip install pca

from pca import pca as pca_lib

model_pca_lib = pca_lib(n_components=0.95)
out = model_pca_lib.fit_transform(X_scaled_df)

Z_df = out["PC"]

print("PCA library principal components head:")
print(out["PC"].head())

print("Original features:", X.shape[1])
print("Encoded features:", X_encoded.shape[1])
print("Reduced features:", Z_df.shape[1])

model_pca_lib.scatter(label=False, legend=True)

plt.savefig("pca_scatter_lib.pdf", bbox_inches="tight")
plt.savefig("pca_scatter_lib.png", dpi=600, bbox_inches="tight")

plt.show()

VR = out['variance_ratio']

x = np.arange(len(VR)) + 1
cumulative_VR = np.cumsum(VR)

plt.figure(figsize=(7,5))

# Individual variance
plt.plot(x, VR, 'o-', lw=2, label="Individual Variance")

# Cumulative variance
plt.plot(x, cumulative_VR, 's--', lw=2, color='red', label="Cumulative Variance")

# Threshold lines
plt.axhline(y=0.85, color='green', linestyle='--', label='85% variance')
plt.axhline(y=0.95, color='purple', linestyle='--', label='95% variance')

plt.xlabel('Number of Components')
plt.ylabel('Explained Variance')
plt.title('Scree Plot (PCA Library)')

plt.legend()
plt.grid(alpha=0.3)

plt.tight_layout()

# Save figures
plt.savefig("scree_plot_pca_lib.pdf", bbox_inches="tight")
plt.savefig("scree_plot_pca_lib.png", dpi=600, bbox_inches="tight")

plt.show()

from google.colab import files
files.download("pca_scatter_lib.png")

model_pca_lib.plot()

plt.savefig("pca_lib.pdf", bbox_inches="tight")
plt.savefig("pca_lib.png", dpi=600, bbox_inches="tight")

plt.show()

from google.colab import files
files.download("pca_lib.png")

model_pca_lib.biplot(label=False, legend=True)

plt.savefig("pca_biplot_lib.pdf", bbox_inches="tight")
plt.savefig("pca_biplot_lib.png", dpi=600, bbox_inches="tight")

plt.show()

from google.colab import files
files.download("pca_biplot_lib.png")

train_model = train_df.drop(columns=["label"]).copy().reset_index(drop=True)
test_model  = test_df.drop(columns=["label"]).copy().reset_index(drop=True)

print(train_model.shape)
print(test_model.shape)
print(train_model["attack_group"].value_counts())
print(test_model["attack_group"].value_counts())

!pip install pycaret

from pycaret.classification import *
clf = setup(data=train_model,test_data=test_model,target="attack_group",session_id=123,index=False)

best_model = compare_models()

xgboost = create_model('xgboost')

tuned_xgboost = tune_model(xgboost)

evaluate_model(tuned_xgboost)

import os
import shutil

plot_model(tuned_xgboost, plot='confusion_matrix', save=True)
shutil.move('Confusion Matrix.png', 'confusion_matrix_xgboost.png')

from google.colab import files
files.download("confusion_matrix_xgboost.png")

et = create_model('et')

tuned_knn = tune_model(knn, custom_grid = {'n_neighbors' : np.arange(0,50,1)})

evaluate_model(tuned_knn)

et = create_model('et')

tuned_et = tune_model(et)

evaluate_model(tuned_et)

rf = create_model('rf')

tuned_rf = tune_model(rf)

evaluate_model(tuned_rf)

from google.colab import files
files.download("confusion_matrix_pca.png")

import os
import shutil

plot_model(tuned_rf, plot='confusion_matrix', save=True)
shutil.move('Confusion Matrix.png', 'confusion_matrix_pca.png')



tuned_best_model = tune_model(best_model)

tuned_best_model

evaluate_model(tuned_best_model)

clf_pca = setup(data=train_model,test_data=test_model,target="attack_group", session_id=123, normalize = True, pca = True, pca_components = 3,index=False)

best_model_pca = compare_models()

tuned_best_model_pca = tune_model(best_model_pca)

evaluate_model(tuned_best_model_pca)

plot_model(tuned_best_model_pca, plot='auc', save=True)

shutil.move('AUC.png', 'roc_curve_pca_et.png')

from google.colab import files
files.download("roc_curve_pca_et.png")

rf_pca = create_model('rf')

tuned_rf_pca = tune_model(rf_pca)

evaluate_model(tuned_rf_pca)

plot_model(tuned_best_model_pca, plot='learning', save=True)
shutil.move('Learning Curve.png', 'learning_curve_rf.png')

from google.colab import files
files.download("learning_curve_rf.png")

knn = create_model('knn')

tuned_knn = tune_model(knn, custom_grid = {'n_neighbors' : np.arange(0,50,1)})

evaluate_model(tuned_knn)

plot_model(tuned_best_model_pca, plot='learning', save=True)
shutil.move('Learning Curve.png', 'learning_curve_knn.png')

from google.colab import files
files.download("learning_curve_knn.png")

xgboost_pca = create_model('xgboost')

tuned_xgboost_pca = tune_model(xgboost_pca)

evaluate_model(tuned_xgboost_pca)

import os
import shutil

plot_model(tuned_xgboost_pca, plot='feature', save=True)
shutil.move('Feature Importance.png', 'feature_importance_pca.png')

from google.colab import files
files.download("feature_importance_pca.png")

!pip install pycaret[analysis]

interpret_model(tuned_rf_pca, plot='summary')

interpret_model(tuned_rf_pca, plot='reason', observation=32, save=True)

interpret_model(tuned_rf_pca, plot='reason')